[server]
port = 5000
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false
address = "0.0.0.0"

[browser]
gatherUsageStats = false
serverPort = 8502

[theme]
primaryColor = "#2E7D32"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#333333"
font = "sans-serif"

[runner]
fastReruns = true
magicEnabled = false

[logger]
level = "error"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
