
[server]
address = "0.0.0.0"
port = 8502
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8502

[theme]
primaryColor = "#2E7D32"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#333333"
font = "sans-serif"

[runner]
fastReruns = true
magicEnabled = false

[client]
toolbarMode = "minimal"
showErrorDetails = false
caching = false

[logger]
level = "error"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
